#!/usr/bin/env bash
set -euo pipefail

# Usage: setup-worktree.sh <worktree-name> <base-branch> [--headless]
# Example: setup-worktree.sh feature-auth master
# Example: setup-worktree.sh fix/123-foo master --headless
#
# --headless skips the iTerm2 launch (for use by automation like b7-issue-to-pr).
# All other behavior (symlinks, port allocation, dev.sh, install) is identical.

HEADLESS=0
POSITIONAL=()
for arg in "$@"; do
  case "$arg" in
    --headless) HEADLESS=1 ;;
    *) POSITIONAL+=("$arg") ;;
  esac
done

if [ "${#POSITIONAL[@]}" -lt 2 ]; then
  echo "Usage: $0 <worktree-name> <base-branch> [--headless]" >&2
  exit 2
fi

WORKTREE_NAME="${POSITIONAL[0]}"
BASE_BRANCH="${POSITIONAL[1]}"

# Precondicion: correr desde el repo PRINCIPAL, no desde un worktree linkeado
# (show-toplevel devolveria el worktree y todo lo demas apuntaria mal).
if [ "$(git rev-parse --git-dir)" != "$(git rev-parse --git-common-dir)" ]; then
  echo "ERROR: ejecutar desde el repo principal, no desde un worktree" >&2
  exit 2
fi

# Resolve the main repo root (where .git lives)
REPO_ROOT="$(git rev-parse --show-toplevel)"
REPO_PARENT="$(dirname "$REPO_ROOT")"

# Paths
# Branch name is exactly what the user provided (may include a prefix like feat/, fix/, etc.)
BRANCH_NAME="${WORKTREE_NAME}"
# Directory name is the last segment after any / to keep the worktrees folder flat
DIR_NAME="${WORKTREE_NAME##*/}"
WORKTREE_DIR="${REPO_PARENT}/worktrees/${DIR_NAME}"

# Check for pending changes — abort if working tree is dirty
if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "ERROR: There are uncommitted changes in the working tree."
  echo "Please commit or stash them before creating a worktree."
  echo ""
  git status --short
  exit 1
fi

# Check for untracked files that might matter
UNTRACKED=$(git ls-files --others --exclude-standard)
if [ -n "$UNTRACKED" ]; then
  echo "WARNING: Untracked files detected (these won't be in the worktree):"
  echo "$UNTRACKED" | head -10
  echo ""
fi

# Validate
if [ -d "$WORKTREE_DIR" ]; then
  echo "ERROR: Worktree directory already exists: $WORKTREE_DIR"
  exit 1
fi

if git show-ref --verify --quiet "refs/heads/${BRANCH_NAME}" 2>/dev/null; then
  echo "ERROR: Branch already exists: $BRANCH_NAME"
  exit 1
fi

echo "Creating worktree..."
echo "  Directory: $WORKTREE_DIR"
echo "  Branch:    $BRANCH_NAME"
echo "  Base:      $BASE_BRANCH"
echo ""

# Create the worktree with a new branch from the base
git worktree add "$WORKTREE_DIR" -b "$BRANCH_NAME" "$BASE_BRANCH"

# Symlink every UNTRACKED .env* file from the main repo (.env, .env.local, etc.)
# Worktrees share secrets/config with the parent so they stay in sync automatically.
# Tracked files (.env.example) se saltan: ln -sf los pisaria con un symlink de path
# absoluto que git ve como type-change -> b3 lo commitearia y romperia el repo remoto.
shopt -s nullglob
for env_file in "${REPO_ROOT}"/.env "${REPO_ROOT}"/.env.*; do
  [ -f "$env_file" ] || continue
  base="$(basename "$env_file")"
  if git -C "$REPO_ROOT" ls-files --error-unmatch "$base" >/dev/null 2>&1; then
    echo "Skipped ${base} (tracked en git; el worktree ya trae su propia copia)"
    continue
  fi
  ln -sf "$env_file" "${WORKTREE_DIR}/${base}"
  echo "Symlinked ${base}"
done
shopt -u nullglob

# Pick a free dev port so this worktree can run alongside the parent and other worktrees.
# Starts at 6026 (parent uses 6025) and walks up until lsof reports nothing listening.
PORT=6026
while lsof -iTCP:"$PORT" -sTCP:LISTEN -P -n >/dev/null 2>&1; do
  PORT=$((PORT + 1))
done
echo "Selected dev port: $PORT"

# Drop a dev.sh shim that launches Vite on the chosen port. Avoids editing package.json
# (which would create a noisy diff). Run with `./dev.sh` from inside the worktree.
cat > "${WORKTREE_DIR}/dev.sh" <<DEVSCRIPT
#!/usr/bin/env bash
# Auto-generated by b1-add-worktree. Runs the dev server on a worktree-specific port
# so it does not collide with the parent repo or sibling worktrees.
exec pnpm exec vite dev --host 0.0.0.0 --port ${PORT} --strictPort "\$@"
DEVSCRIPT
chmod +x "${WORKTREE_DIR}/dev.sh"
echo "Created dev.sh shim (port ${PORT})"

# Seed a PER-WORKTREE git exclude so worktree-local artifacts (.b7/, dev.sh,
# logs, screenshots) never dirty `git status` IN THIS WORKTREE ONLY. We avoid
# the shared info/exclude on purpose: wildcards like *.log there would hide
# files in the MAIN repo's git status too (and in every sibling worktree).
# NOTE: core.excludesFile (worktree scope) overrides the user's global
# excludesFile for this worktree — common global patterns (.DS_Store) are
# included below so nothing is lost.
# Patrones ANCLADOS a raiz con "/" — sin anclar, gitignore matchea a cualquier
# profundidad y ocultaria archivos legitimos (ej. tests/fixtures/expected.log).
# .DS_Store queda global a proposito (nunca es codigo).
git -C "$WORKTREE_DIR" config extensions.worktreeConfig true
git -C "$WORKTREE_DIR" config --worktree core.excludesFile "${WORKTREE_DIR}/.git-worktree-exclude"
printf '%s\n' '/.b7/' '/dev.sh' '/*.log' '.DS_Store' '/dev-server.pid' '/.playwright-mcp/' '/.git-worktree-exclude' \
  > "${WORKTREE_DIR}/.git-worktree-exclude"
echo "Seeded per-worktree git exclude (${WORKTREE_DIR}/.git-worktree-exclude)"

# --- Install the b7 pre-commit budget hook (WORKTREE-SCOPED) ---
# Rejects commits that touch denylisted paths (package.json, lockfiles, env, infra,
# CI, *.sh) or blow the file-count budget. Scoped to THIS worktree via core.hooksPath
# so the main repo and sibling worktrees are untouched. The generated hook CHAINS to
# the repo's prior pre-commit (husky/lefthook/native) first, so lint-staged etc. still
# run. Without this install the denylist in b7's SKILL was a claim with no enforcement.
SETUP_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-$(cd "$SETUP_SCRIPT_DIR/../../.." && pwd)}"
BUDGET_HOOK_SRC="$PLUGIN_ROOT/skills/b7-issue-to-pr/hooks/pre-commit-budget.sh"
if [ -f "$BUDGET_HOOK_SRC" ]; then
  # Resolve the repo's existing pre-commit so we can chain to it (do NOT clobber husky).
  PRIOR_HOOKS_DIR="$(git -C "$REPO_ROOT" config --get core.hooksPath || true)"
  [ -z "$PRIOR_HOOKS_DIR" ] && PRIOR_HOOKS_DIR="$(git -C "$REPO_ROOT" rev-parse --git-common-dir)/hooks"
  case "$PRIOR_HOOKS_DIR" in
    /*) : ;;                                   # absolute, use as-is
    *)  PRIOR_HOOKS_DIR="${REPO_ROOT}/${PRIOR_HOOKS_DIR}" ;;  # husky uses a relative path
  esac
  PRIOR_PRECOMMIT="${PRIOR_HOOKS_DIR}/pre-commit"

  WT_HOOKS_DIR="${WORKTREE_DIR}/.b7/git-hooks"
  mkdir -p "$WT_HOOKS_DIR"
  cat > "${WT_HOOKS_DIR}/pre-commit" <<HOOK
#!/usr/bin/env bash
# Auto-generated by b1-add-worktree/setup-worktree.sh. Chains the repo's prior
# pre-commit (if any), then enforces the b7 file/path budget. Worktree-scoped.
set -euo pipefail
PRIOR="${PRIOR_PRECOMMIT}"
if [ -x "\$PRIOR" ] && [ "\$PRIOR" != "\$0" ]; then
  "\$PRIOR" "\$@" || exit \$?
fi
exec bash "${BUDGET_HOOK_SRC}" "\$@"
HOOK
  chmod +x "${WT_HOOKS_DIR}/pre-commit"
  git -C "$WORKTREE_DIR" config --worktree core.hooksPath "$WT_HOOKS_DIR"
  if [ -x "$PRIOR_PRECOMMIT" ]; then
    echo "Installed b7 budget pre-commit hook (worktree-scoped; chains ${PRIOR_PRECOMMIT})"
  else
    echo "Installed b7 budget pre-commit hook (worktree-scoped; no prior pre-commit to chain)"
  fi
else
  echo "WARNING: budget hook source not found at ${BUDGET_HOOK_SRC} — commit budget NOT enforced" >&2
fi

# Install dependencies in the worktree
echo "Installing dependencies..."
(cd "$WORKTREE_DIR" && pnpm install --frozen-lockfile)
echo "Dependencies installed"

echo ""
echo "Worktree ready at: $WORKTREE_DIR"
echo "Branch:            $BRANCH_NAME"
echo "Dev port:          $PORT  (run ./dev.sh — NOT pnpm dev, which is hardcoded to 6025)"
echo ""

# Drop a marker file that proves this script ran end-to-end. Consumers (b7-issue-to-pr's
# guardrails.sh verify-worktree) check for this file to refuse worktrees created by
# direct `git worktree add` calls.
mkdir -p "${WORKTREE_DIR}/.b7"
ENV_LINKS=$(cd "$WORKTREE_DIR" && find . -maxdepth 1 -name '.env*' -type l | sed 's|^\./||' | paste -sd, -)
cat > "${WORKTREE_DIR}/.b7/worktree-ready.json" <<MARKER
{
  "dir": "${WORKTREE_DIR}",
  "branch": "${BRANCH_NAME}",
  "base": "${BASE_BRANCH}",
  "port": ${PORT},
  "env_symlinks": "${ENV_LINKS}",
  "created_by": "b1-add-worktree/setup-worktree.sh",
  "created_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
MARKER

# Open a new iTerm2 session in the worktree folder (skipped in headless mode)
if [ "$HEADLESS" -eq 1 ]; then
  echo "Headless mode: skipping iTerm2 launch."
  # Final machine-parseable line for automation. Format is stable; do not change without
  # updating consumers (b7-issue-to-pr).
  echo "WORKTREE_READY dir=${WORKTREE_DIR} branch=${BRANCH_NAME} port=${PORT}"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  osascript <<APPLESCRIPT
tell application "iTerm2"
  create window with default profile
  tell current session of current window
    write text "cd '${WORKTREE_DIR}'"
  end tell
end tell
APPLESCRIPT
  echo "Opened new iTerm2 session in worktree."
else
  echo "NOTE: Auto-open terminal is only supported on macOS."
  echo "Please cd to: $WORKTREE_DIR"
fi
